version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/app
    environment:
      - NODE_ENV=development

  backend:
    build: ./backend
    ports:
      - '8000:8000'
    volumes:
      - ./backend:/app
    environment:
      - DJANGO_ENV=development

  ai-service:
    build: ./ai-modules
    ports:
      - '5000:5000'
    volumes:
      - ./ai-modules:/app
